### ISSUE TITLE
project

### ISSUE THREAD

**Issue by daviddias** [websound/example#1]
![image](https://cloud.githubusercontent.com/assets/1211152/10748477/5b5ba2ea-7c58-11e5-9172-47ae83c78024.png)

**Comment by obensource** [comment]
## Updated Abstract

![project update](http://i.imgur.com/6Wm3OBu.jpg)

**Comment by obensource** [comment]
## Remote-Performer Demo
1. Fork [this project](https://github.com/natevw/midisocket) (originally from [here](https://github.com/vine77/midisocket))
2. 'Swap' the socket.io server for a peer.js server
   - Use [David's](https://github.com/websound/example) simple peer-server and dependencies 
3. Refactor MIDI & Audio contexts for demo use case
4. Refactor front-end/back-end module system separation into only using npm, add webpack for bundling.

@diasdavid @natevw
