### ISSUE TITLE
'Swap' socket.io server for peer.js server

### ISSUE THREAD

**Issue by obensource** [websound/example#3]
1. Update Bower dependencies in fork
2. Replace socket.io server with existing [peer-server](https://github.com/websound/example/blob/master/src/index.js#L1)

@diasdavid

**Comment by daviddias** [comment]
How we can connect both peers through peerJS if we don't know ahead the other peer ID in the peerJS world?

**Comment by obensource** [comment]
@diasdavid that's a good question. To be practical we'd need a user registry broadcast to all clients based on who has the app open (in order to choose a peer to ask to connect to) which we can later add auth and a 'friends' service to. For the first simple demo though we'll have to have the user get the peer ID from the other person they intend to play with and manually enter it in a form on a splash page? If you have a better idea let me know, but it doesn't have to be better than that for demoing, imo. We just need to connect two of us as easily as possible atm.
